name: ht_data_api
description: A generic Dart package providing an implementation of HtDataClient for interacting with data resource endpoints via ht_http_client.
repository: https://github.com/headlines-toolkit/ht-data-api
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ht_data_client:
    git:
      url: https://github.com/headlines-toolkit/ht-data-client.git
  ht_http_client:
    git:
      url: https://github.com/headlines-toolkit/ht-http-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^9.0.0
